
const actionTypes = {
    LOGIN_PROGRESS : 'LOGIN_PROGRESS',
    LOGIN_SUCCEED : 'LOGIN_SUCCEED',
    SIGNUP_PROGRESS : 'SIGNUP_PROGRESS',
    SIGNUP_SUCCEED : 'SIGNUP_SUCCEED',
    LOGOUT_SUCCEED : 'LOGOUT_SUCCEED',
    LOGIN_ERROR: 'LOGIN_ERROR',
    SIGNUP_ERROR : 'SIGNUP_ERROR',
    SIGNUP_ERROR_ALERT : 'SIGNUP_ERROR_ALERT',
    LOGIN_ERROR_ALERT : 'LOGIN_ERROR_ALERT',
    STORE_USERS_DATA: 'STORE_USERS_DATA',
    LOAD_STORE: 'LOAD_STORE',
    LOAD_STORE_STATE: 'LOAD_STORE_STATE'
}
export default actionTypes;